version: '3'
services:

  apichimistreta:
    image: apichimistreta
    hostname: apichimistreta
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - panel_v1
    ports:
      - 5000:5001

networks:
  panel_v1:
